# Generated by Django 4.2.1 on 2023-07-06 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Post ID')),
                ('post_text', models.TextField(help_text='Enter the text for the post.', verbose_name='Post Text')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Likes Count')),
                ('views_count', models.IntegerField(default=0, verbose_name='Views Count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
