# Generated by Django 4.2.1 on 2023-07-06 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(help_text='Upload a profile picture.', upload_to='profile_pictures', verbose_name='Profile Picture')),
                ('account_created', models.DateTimeField(auto_now_add=True, help_text='The date and time when the account was created.', verbose_name='Account Created')),
                ('bio', models.TextField(blank=True, help_text='Enter a short bio about yourself.', verbose_name='Bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
